tasks:
  - before: cd setup-from-scratch
    init: npm install 
    command: npm start
  - before: cd setup-from-create-react-app
    init: npm install 
    command: npm start
ports:
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: open-preview